# application.yml

spring:
  profiles:
    active: dev
  application:
    name: whoami-service

ssms:
  common:
    sentry-dsn: https://61ec95763d22ef304b11bc25b4b6d70f@o4508115831160832.ingest.us.sentry.io/4508115835420672
    deploy-env: ${DEPLOY:V2}
  company-service-endpoint: http://company-service:8080
  account-service-endpoint: http://account-service:8080
  intercom-app-id: ${INTERCOM_APP_ID}
  intercom-signing-secret: ${INTERCOM_SIGNING_SECRET}
