# application.yml

spring:
  profiles:
    active: dev
  application:
    name: email-service

ssms:
  common:
    sentry-dsn: https://61ec95763d22ef304b11bc25b4b6d70f@o4508115831160832.ingest.us.sentry.io/4508115835420672
    deploy-env: ${DEPLOY:V2}
  aliyun-access-key: LTAI5tK46ifstsHUbCryiZCg
  aliyun-access-secret: o4G6WvPQMl4k8ZTkMDp4M8tB49wsL2
