spring:
  datasource:
    url: jdbc:mysql://152.42.192.36:3306/ssms_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 451254
  jpa:
    show-sql: true
server:
  port: 8081
ssms:
  email-service-endpoint: http://mail-svc:8088
  company-service-endpoint: http://company-svc:8082
  bot-service-endpoint: http://bot-svc:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
