# application.yml

spring:
  profiles:
    active: dev
  application:
    name: faraday-service

server:
  error:
    whitelabel:
      enabled: false

ssms:
  common:
    sentry-dsn: https://61ec95763d22ef304b11bc25b4b6d70f@o4508115831160832.ingest.us.sentry.io/4508115835420672
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}

