spring:
  datasource:
    url: jdbc:mysql://152.42.192.36:3306/ssms_company?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 451254
  jpa:
    show-sql: true
server:
  port: 8082

ssms:
  email-service-endpoint: http://localhost:8088
  account-service-endpoint: http://localhost:8081
  bot-service-endpoint: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"