# application.yml

spring:
  profiles:
    active: dev
  application:
    name: company-service
  datasource:
    url: ${COMPANY_DATASOURCE_URL}
    username: ${COMPANY_DATASOURCE_USERNAME}
    password: ${COMPANY_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate

ssms:
  common:
    sentry-dsn: https://61ec95763d22ef304b11bc25b4b6d70f@o4508115831160832.ingest.us.sentry.io/4508115835420672
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-servie:8080}
  bot-service-endpoint: ${BOT_SERVICE_ENDPOINT:http://bot-service:8080}