# application.yml

spring:
  profiles:
    active: dev
  application:
    name: www-service

server:
  error:
    whitelabel:
      enabled: false

ssms:
  common:
    sentry-dsn: https://61ec95763d22ef304b11bc25b4b6d70f@o4508115831160832.ingest.us.sentry.io/4508115835420672
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}
  company-service-endpoint: ${COMPANY_SERVICE_ENDPOINT:http://company-service:8080}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-service:8080}
  recaptcha-public: ${RECAPTCHA_PUBLIC}
  recaptcha-private: ${RECAPTCHA_PRIVATE}