spring:
  thymeleaf:
    cache: false # Disable template caching for local development

server:
  port: 8086

ssms:
  email-service-endpoint: http://mail-svc:8088
  company-service-endpoint: http://company-svc:8082
  account-service-endpoint: http://account-svc:8081
